### ISSUE TITLE
bumping snapshot/build version in CI only

### ISSUE THREAD

**Issue by ducin** [mgol/npm-bump#12]
Cześć Michał :)

I've got a usecase with managing npm package versions and I'm not sure whether it matches with you `npm-bump` library. I would like a CI server (e.g. jenkins, travis, etc) to build my app, run tests and then publish it - for each build, I need to have all snapshots. For this reason, I have to bump up package.json's `version` each time. Doing it manually is practically undoable, so I was looking for something like: `npm bump ${MyCIBuildNumber}` which would automatically update the version without saving it back in git.

Do you think it matches the purpose of this lib? I need no actual git actions performed, no npm publish, just to update version with a value from CLI.

**Comment by mgol** [comment]
Cześć :)

> I was looking for something like: npm bump ${MyCIBuildNumber} which would automatically update the version without saving it back in git.
> 
> (...) I need no actual git actions performed, no npm publish, just to update version with a value from CLI.

Do I understand correctly that you want to update a version in `package.json` and then do your own custom publish logic with absolutely no Git/npm operations? This doesn't look exactly like something that's a purpose of this lib...

Is the following all that you need?

1. Read `package.json` via `fs.readFile` & `JSON.parse` the contents.
2. Swap the `version` field for the value you provided.
3. `JSON.stringify` the resulting object and write it using `fs.writeFile`.

Why is it undoable?

**Comment by ducin** [comment]
Yep, you understand it 100% correctly. Of course, *it is doable*, just having the same script (read-modify-write) being copied into multiple JS repos (within the same CI system) lead to publishing it as a standalone, tiny package. And that leads to another question - maybe it already is (or might be) a part of an existing package :) the name `bump` also matches it pretty well.

I take your answer as _no, my aim described above is beoynd the scope of this lib_.

**Comment by mgol** [comment]
This `swap-value-and-write-back` does look like a material for a separate package. :) I don't think there's an easy way to do it as part of this one, it works at a higher level. I could only make `npm publish` optional but skipping Git completely seems not to fit well with the overall functionality. I'll close this issue then.
