### ISSUE TITLE
an option to prefix commit messages

### ISSUE THREAD

**Issue by viqueen** [mgol/npm-bump#4]

**Comment by mgol** [comment]
Prefix seems very specific... How about being able to provide the full template for the commit message? Or do you think that's too much?

**Comment by viqueen** [comment]
Passing a template could also work, but it might be too much. 
In most cases build/general scripts grep for a keyword or issue numbers or a pattern, in which case a prefix would work just fine, it doesn't matter what the rest of the commit message really is.
(and the current default is good enough)
